version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: versionintel-db-prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - versionintel-network
    security_opt:
      - no-new-privileges:true

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: versionintel-backend-prod
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - NVD_API_KEY=${NVD_API_KEY}
      - AI_PROVIDER=${AI_PROVIDER}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_MODEL=${GOOGLE_MODEL}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - logs:/var/log/versionintel
    networks:
      - versionintel-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile.production
      args:
        - REACT_APP_API_URL=https://${PRODUCTION_DOMAIN}:8000
        - REACT_APP_ENVIRONMENT=production
    container_name: versionintel-frontend-prod
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - versionintel-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run

  # Nginx reverse proxy removed - direct access to services

volumes:
  postgres_data:
    driver: local
  logs:
    driver: local


networks:
  versionintel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16