services:
  db:
    image: postgres:13-alpine
    container_name: versionintel-db-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-versionintel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-versionintel123}
      POSTGRES_DB: ${POSTGRES_DB:-versionintel}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-versionintel} -d ${POSTGRES_DB:-versionintel}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - versionintel-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: versionintel-backend-dev
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-versionintel}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-versionintel123}
      - POSTGRES_DB=${POSTGRES_DB:-versionintel}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-jwt-secret}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - AI_PROVIDER=${AI_PROVIDER:-gemini}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_MODEL=${GOOGLE_MODEL:-gemini-2.0-flash}
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./backend:/app
    networks:
      - versionintel-network

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: versionintel-frontend-dev
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_ENVIRONMENT=development
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - versionintel-network

volumes:
  postgres_data_dev:
    driver: local

networks:
  versionintel-network:
    driver: bridge