blank_issues_enabled: false
contact_links:
  - name: VersionIntel Documentation
    url: https://github.com/your-username/versionintel/blob/main/docs/README.md
    about: Check our documentation for help with installation, usage, and troubleshooting
  - name: Community Discussions
    url: https://github.com/your-username/versionintel/discussions
    about: Ask questions, share ideas, and connect with other VersionIntel users
  - name: Security Issues
    url: security@versionintel.org
    about: Report security vulnerabilities responsibly (do not use public issues)